name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: dalglish14/concourse-dcind

jobs:
  pr_check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-test

  build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: echo "current_version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ env.current_version }}
          new_version=$(echo $current_version | awk -F. '{printf("v%d.%d.%d", $1, $2+1, $3)}')
          echo "New version: $new_version"
          echo $new_version > VERSION
          echo $new_version > temp_version.txt
          echo "new_version=$new_version" >> $GITHUB_ENV
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b version-bump-$new_version
          git add VERSION
          git commit -m "Bump version to $new_version"
        shell: bash

      - name: Fetch, rebase, and push new branch
        run: |
          git fetch origin
          git rebase origin/version-bump-${{ env.new_version }}
          git push origin HEAD:version-bump-${{ env.new_version }}
        shell: bash

      - name: Merge and push version bump commit and tag
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff version-bump-${{ env.new_version }}
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: dalglish14
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,pattern=main,tag=latest
            type=ref,event=semver,pattern=${{ env.new_version }},prefix=v

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
