name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: dalglish14/concourse-dcind

jobs:
  pr_check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-test

  version_bump:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(cat VERSION)"

      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ steps.get_version.outputs.current_version }}
          new_version=$(echo $current_version | awk -F. '{printf("v%d.%d.%d", $1, $2+1, $3)}')
          echo "New version: $new_version"
          echo $new_version > VERSION
          echo $new_version > temp_version.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b version-bump-${{ new_version }}
          git add VERSION
          git commit -m "Bump version to $new_version"
          echo "::set-output name=new_version::$new_version"
        shell: bash

      - name: Fetch, rebase, and push new branch
        run: |
          git fetch origin
          git rebase origin/main
          git push origin HEAD:version-bump-${{ steps.increment_version.outputs.new_version }}
        shell: bash

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-branch: version-bump-${{ steps.increment_version.outputs.new_version }}
          base-branch: main
          title: Bump version to ${{ steps.increment_version.outputs.new_version }}
          body: |
            This PR bumps the version to ${{ steps.increment_version.outputs.new_version }}.
          labels: version bump

  build_and_push:
    runs-on: ubuntu-latest
    needs: version_bump
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: dalglish14
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,pattern=main,tag=latest
            type=ref,event=tag,pattern=v*.*.*,tag={{version}}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Merge and push version bump commit and tag
        run: |
          git fetch --all
          git checkout main
          new_version=$(cat temp_version.txt)
          git merge origin/version-bump-${{ needs.version_bump.outputs.new_version }} --no-ff
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
