name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed

env:
  REGISTRY: docker.io
  IMAGE_NAME: dalglish14/concourse-dcind

jobs:
  pr_check:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-test

  version_bump:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine next version
        id: determine_version
        run: |
          mkdir -p tmp
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            latest_tag=$(git describe --tags --abbrev=0)
            latest_version=$(echo $latest_tag | sed 's/v//')
            IFS='.' read -r -a version_parts <<< "$latest_version"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
            new_patch=$((patch + 1))
            new_version="v${major}.${minor}.${new_patch}"
          else
            new_version="v0.1.0"
          fi
          echo "New version: $new_version"
          echo $new_version > tmp/version.txt
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit version file
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b version-bump-${{ env.new_version }}
          git add tmp/version.txt
          git commit -m "Add version file with new version ${{ env.new_version }}"
          git push origin HEAD:version-bump-${{ env.new_version }}
        shell: bash

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-branch: version-bump-${{ env.new_version }}
          base-branch: main
          title: Bump version to ${{ env.new_version }}
          body: |
            This PR bumps the version to ${{ env.new_version }}.
          labels: version bump

  build_and_push:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.event.pull_request.head.ref, 'version-bump-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: echo "current_version=$(cat tmp/version.txt)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: dalglish14
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,pattern=main,tag=latest
            type=ref,event=semver,pattern=${{ env.current_version }},prefix=v

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
